### ISSUE TITLE
How much VRAM is needed for this?

### ISSUE THREAD

**Issue by Echo411** [ubc-vision/Make-A-Story#1]
This looks great!

Could you share some information on what setup you used for the training of the transformer model?

1. how many gpu / for how long
2. how many steps
3. what batch size

It would be helpful to have these information to better understand the cost of training models.

**Comment by trahman8** [comment]
1. We used one GPU which is A600. 
2. Mugen is a large dataset that took longer to train. We used 3 epochs for the dataset. For other two we used 100+ epochs.
3. For Mugen, flintstone and proro we used batch size 24, 12 and 16 respectively.
