### ISSUE TITLE
train-val-test_split.json missing

### ISSUE THREAD

**Issue by Starfish2018** [ubc-vision/Make-A-Story#5]
Hello, can you please help me to find this file? I need to evaluate and retrain your model . Thanks for help.

Make-A-Story\ldm\data\flintstones_data.py", line 27, in story_dataset
    splits = json.load(open(os.path.join(self.dir_path, 'train-val-test_split.json'), 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/ubc/cs/research/shield/projects/trahman8/snap_research/flintstones_data\\train-val-test_split.json'

**Comment by Starfish2018** [comment]
following up on this request. would appreciate your guidance.

**Comment by trahman8** [comment]
This file is the same as the original flintstones dataset.
